//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доп настройки.
    /// </summary>
    // *** Start programmer edit section *** (ДопНастройки CustomAttributes)

    // *** End programmer edit section *** (ДопНастройки CustomAttributes)
    [AutoAltered()]
    [Caption("Доп настройки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДопНастройкиE", new string[] {
            "Кадрирование as \'Кадрирование\'",
            "ЧБЦвет as \'Ч б цвет\'",
            "Уголок as \'Уголок\'"})]
    public class ДопНастройки : ICSSoft.STORMNET.DataObject
    {
        
        private bool fКадрирование;
        
        private bool fЧБЦвет;
        
        private bool fУголок;
        
        private IIS.Kursovaya3.ПечатьФото fПечатьФото;
        
        // *** Start programmer edit section *** (ДопНастройки CustomMembers)

        // *** End programmer edit section *** (ДопНастройки CustomMembers)

        
        /// <summary>
        /// Кадрирование.
        /// </summary>
        // *** Start programmer edit section *** (ДопНастройки.Кадрирование CustomAttributes)

        // *** End programmer edit section *** (ДопНастройки.Кадрирование CustomAttributes)
        public virtual bool Кадрирование
        {
            get
            {
                // *** Start programmer edit section *** (ДопНастройки.Кадрирование Get start)

                // *** End programmer edit section *** (ДопНастройки.Кадрирование Get start)
                bool result = this.fКадрирование;
                // *** Start programmer edit section *** (ДопНастройки.Кадрирование Get end)

                // *** End programmer edit section *** (ДопНастройки.Кадрирование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопНастройки.Кадрирование Set start)

                // *** End programmer edit section *** (ДопНастройки.Кадрирование Set start)
                this.fКадрирование = value;
                // *** Start programmer edit section *** (ДопНастройки.Кадрирование Set end)

                // *** End programmer edit section *** (ДопНастройки.Кадрирование Set end)
            }
        }
        
        /// <summary>
        /// Уголок.
        /// </summary>
        // *** Start programmer edit section *** (ДопНастройки.Уголок CustomAttributes)

        // *** End programmer edit section *** (ДопНастройки.Уголок CustomAttributes)
        public virtual bool Уголок
        {
            get
            {
                // *** Start programmer edit section *** (ДопНастройки.Уголок Get start)

                // *** End programmer edit section *** (ДопНастройки.Уголок Get start)
                bool result = this.fУголок;
                // *** Start programmer edit section *** (ДопНастройки.Уголок Get end)

                // *** End programmer edit section *** (ДопНастройки.Уголок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопНастройки.Уголок Set start)

                // *** End programmer edit section *** (ДопНастройки.Уголок Set start)
                this.fУголок = value;
                // *** Start programmer edit section *** (ДопНастройки.Уголок Set end)

                // *** End programmer edit section *** (ДопНастройки.Уголок Set end)
            }
        }
        
        /// <summary>
        /// ЧБЦвет.
        /// </summary>
        // *** Start programmer edit section *** (ДопНастройки.ЧБЦвет CustomAttributes)

        // *** End programmer edit section *** (ДопНастройки.ЧБЦвет CustomAttributes)
        public virtual bool ЧБЦвет
        {
            get
            {
                // *** Start programmer edit section *** (ДопНастройки.ЧБЦвет Get start)

                // *** End programmer edit section *** (ДопНастройки.ЧБЦвет Get start)
                bool result = this.fЧБЦвет;
                // *** Start programmer edit section *** (ДопНастройки.ЧБЦвет Get end)

                // *** End programmer edit section *** (ДопНастройки.ЧБЦвет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопНастройки.ЧБЦвет Set start)

                // *** End programmer edit section *** (ДопНастройки.ЧБЦвет Set start)
                this.fЧБЦвет = value;
                // *** Start programmer edit section *** (ДопНастройки.ЧБЦвет Set end)

                // *** End programmer edit section *** (ДопНастройки.ЧБЦвет Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya3.ПечатьФото.
        /// </summary>
        // *** Start programmer edit section *** (ДопНастройки.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (ДопНастройки.ПечатьФото CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПечатьФото"})]
        public virtual IIS.Kursovaya3.ПечатьФото ПечатьФото
        {
            get
            {
                // *** Start programmer edit section *** (ДопНастройки.ПечатьФото Get start)

                // *** End programmer edit section *** (ДопНастройки.ПечатьФото Get start)
                IIS.Kursovaya3.ПечатьФото result = this.fПечатьФото;
                // *** Start programmer edit section *** (ДопНастройки.ПечатьФото Get end)

                // *** End programmer edit section *** (ДопНастройки.ПечатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопНастройки.ПечатьФото Set start)

                // *** End programmer edit section *** (ДопНастройки.ПечатьФото Set start)
                this.fПечатьФото = value;
                // *** Start programmer edit section *** (ДопНастройки.ПечатьФото Set end)

                // *** End programmer edit section *** (ДопНастройки.ПечатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДопНастройкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопНастройкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопНастройкиE", typeof(IIS.Kursovaya3.ДопНастройки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ДопНастройки.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfДопНастройки CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfДопНастройки CustomAttributes)
    public class DetailArrayOfДопНастройки : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya3.DetailArrayOfДопНастройки members)

        // *** End programmer edit section *** (IIS.Kursovaya3.DetailArrayOfДопНастройки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ДопНастройки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ДопНастройки.
        /// </summary>
        public DetailArrayOfДопНастройки(IIS.Kursovaya3.ПечатьФото fПечатьФото) : 
                base(typeof(ДопНастройки), ((ICSSoft.STORMNET.DataObject)(fПечатьФото)))
        {
        }
        
        public IIS.Kursovaya3.ДопНастройки this[int index]
        {
            get
            {
                return ((IIS.Kursovaya3.ДопНастройки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya3.ДопНастройки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
