//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать фото.
    /// </summary>
    // *** Start programmer edit section *** (ПечатьФото CustomAttributes)

    // *** End programmer edit section *** (ПечатьФото CustomAttributes)
    [AutoAltered()]
    [Caption("Печать фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьФотоE", new string[] {
            "РазмерВСм as \'Размер в см\'",
            "Носитель as \'Носитель\'",
            "Количество as \'Количество\'"})]
    [AssociatedDetailViewAttribute("ПечатьФотоE", "ДопНастройки", "ДопНастройкиE", true, "", "Доп настройки", true, new string[] {
            ""})]
    [View("ПечатьФотоL", new string[] {
            "РазмерВСм as \'Размер в см\'",
            "Носитель as \'Носитель\'",
            "Количество as \'Количество\'"})]
    public class ПечатьФото : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovaya3.ВыборРазмера fРазмерВСм;
        
        private IIS.Kursovaya3.ВидНосителя fНоситель;
        
        private int fКоличество;
        
        private IIS.Kursovaya3.DetailArrayOfДопНастройки fДопНастройки;
        
        // *** Start programmer edit section *** (ПечатьФото CustomMembers)

        // *** End programmer edit section *** (ПечатьФото CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Количество CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Количество Get start)

                // *** End programmer edit section *** (ПечатьФото.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ПечатьФото.Количество Get end)

                // *** End programmer edit section *** (ПечатьФото.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Количество Set start)

                // *** End programmer edit section *** (ПечатьФото.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ПечатьФото.Количество Set end)

                // *** End programmer edit section *** (ПечатьФото.Количество Set end)
            }
        }
        
        /// <summary>
        /// Носитель.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.Носитель CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.Носитель CustomAttributes)
        public virtual IIS.Kursovaya3.ВидНосителя Носитель
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.Носитель Get start)

                // *** End programmer edit section *** (ПечатьФото.Носитель Get start)
                IIS.Kursovaya3.ВидНосителя result = this.fНоситель;
                // *** Start programmer edit section *** (ПечатьФото.Носитель Get end)

                // *** End programmer edit section *** (ПечатьФото.Носитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.Носитель Set start)

                // *** End programmer edit section *** (ПечатьФото.Носитель Set start)
                this.fНоситель = value;
                // *** Start programmer edit section *** (ПечатьФото.Носитель Set end)

                // *** End programmer edit section *** (ПечатьФото.Носитель Set end)
            }
        }
        
        /// <summary>
        /// РазмерВСм.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.РазмерВСм CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.РазмерВСм CustomAttributes)
        public virtual IIS.Kursovaya3.ВыборРазмера РазмерВСм
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.РазмерВСм Get start)

                // *** End programmer edit section *** (ПечатьФото.РазмерВСм Get start)
                IIS.Kursovaya3.ВыборРазмера result = this.fРазмерВСм;
                // *** Start programmer edit section *** (ПечатьФото.РазмерВСм Get end)

                // *** End programmer edit section *** (ПечатьФото.РазмерВСм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.РазмерВСм Set start)

                // *** End programmer edit section *** (ПечатьФото.РазмерВСм Set start)
                this.fРазмерВСм = value;
                // *** Start programmer edit section *** (ПечатьФото.РазмерВСм Set end)

                // *** End programmer edit section *** (ПечатьФото.РазмерВСм Set end)
            }
        }
        
        /// <summary>
        /// Печать фото.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьФото.ДопНастройки CustomAttributes)

        // *** End programmer edit section *** (ПечатьФото.ДопНастройки CustomAttributes)
        public virtual IIS.Kursovaya3.DetailArrayOfДопНастройки ДопНастройки
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьФото.ДопНастройки Get start)

                // *** End programmer edit section *** (ПечатьФото.ДопНастройки Get start)
                if ((this.fДопНастройки == null))
                {
                    this.fДопНастройки = new IIS.Kursovaya3.DetailArrayOfДопНастройки(this);
                }
                IIS.Kursovaya3.DetailArrayOfДопНастройки result = this.fДопНастройки;
                // *** Start programmer edit section *** (ПечатьФото.ДопНастройки Get end)

                // *** End programmer edit section *** (ПечатьФото.ДопНастройки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьФото.ДопНастройки Set start)

                // *** End programmer edit section *** (ПечатьФото.ДопНастройки Set start)
                this.fДопНастройки = value;
                // *** Start programmer edit section *** (ПечатьФото.ДопНастройки Set end)

                // *** End programmer edit section *** (ПечатьФото.ДопНастройки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоE", typeof(IIS.Kursovaya3.ПечатьФото));
                }
            }
            
            /// <summary>
            /// "ПечатьФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьФотоL", typeof(IIS.Kursovaya3.ПечатьФото));
                }
            }
        }
    }
}
