//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Печать чека.
    /// </summary>
    // *** Start programmer edit section *** (ПечатьЧека CustomAttributes)

    // *** End programmer edit section *** (ПечатьЧека CustomAttributes)
    [AutoAltered()]
    [Caption("Печать чека")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПечатьЧекаE", new string[] {
            "ИннОрг as \'Инн орг\'",
            "Компания as \'Компания\'"})]
    [View("ПечатьЧекаL", new string[] {
            "ИннОрг as \'Инн орг\'",
            "Компания as \'Компания\'"})]
    public class ПечатьЧека : ICSSoft.STORMNET.DataObject
    {
        
        private int fИннОрг;
        
        private string fКомпания;
        
        private IIS.Kursovaya3.ПечатьФото fПечатьФото;
        
        private IIS.Kursovaya3.Оплата fОплата;
        
        // *** Start programmer edit section *** (ПечатьЧека CustomMembers)

        // *** End programmer edit section *** (ПечатьЧека CustomMembers)

        
        /// <summary>
        /// ИннОрг.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьЧека.ИннОрг CustomAttributes)

        // *** End programmer edit section *** (ПечатьЧека.ИннОрг CustomAttributes)
        public virtual int ИннОрг
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьЧека.ИннОрг Get start)

                // *** End programmer edit section *** (ПечатьЧека.ИннОрг Get start)
                int result = this.fИннОрг;
                // *** Start programmer edit section *** (ПечатьЧека.ИннОрг Get end)

                // *** End programmer edit section *** (ПечатьЧека.ИннОрг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьЧека.ИннОрг Set start)

                // *** End programmer edit section *** (ПечатьЧека.ИннОрг Set start)
                this.fИннОрг = value;
                // *** Start programmer edit section *** (ПечатьЧека.ИннОрг Set end)

                // *** End programmer edit section *** (ПечатьЧека.ИннОрг Set end)
            }
        }
        
        /// <summary>
        /// Компания.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьЧека.Компания CustomAttributes)

        // *** End programmer edit section *** (ПечатьЧека.Компания CustomAttributes)
        [StrLen(255)]
        public virtual string Компания
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьЧека.Компания Get start)

                // *** End programmer edit section *** (ПечатьЧека.Компания Get start)
                string result = this.fКомпания;
                // *** Start programmer edit section *** (ПечатьЧека.Компания Get end)

                // *** End programmer edit section *** (ПечатьЧека.Компания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьЧека.Компания Set start)

                // *** End programmer edit section *** (ПечатьЧека.Компания Set start)
                this.fКомпания = value;
                // *** Start programmer edit section *** (ПечатьЧека.Компания Set end)

                // *** End programmer edit section *** (ПечатьЧека.Компания Set end)
            }
        }
        
        /// <summary>
        /// Печать чека.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьЧека.Оплата CustomAttributes)

        // *** End programmer edit section *** (ПечатьЧека.Оплата CustomAttributes)
        [PropertyStorage(new string[] {
                "Оплата"})]
        [NotNull()]
        public virtual IIS.Kursovaya3.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьЧека.Оплата Get start)

                // *** End programmer edit section *** (ПечатьЧека.Оплата Get start)
                IIS.Kursovaya3.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (ПечатьЧека.Оплата Get end)

                // *** End programmer edit section *** (ПечатьЧека.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьЧека.Оплата Set start)

                // *** End programmer edit section *** (ПечатьЧека.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (ПечатьЧека.Оплата Set end)

                // *** End programmer edit section *** (ПечатьЧека.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Печать чека.
        /// </summary>
        // *** Start programmer edit section *** (ПечатьЧека.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (ПечатьЧека.ПечатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "ПечатьФото"})]
        [NotNull()]
        public virtual IIS.Kursovaya3.ПечатьФото ПечатьФото
        {
            get
            {
                // *** Start programmer edit section *** (ПечатьЧека.ПечатьФото Get start)

                // *** End programmer edit section *** (ПечатьЧека.ПечатьФото Get start)
                IIS.Kursovaya3.ПечатьФото result = this.fПечатьФото;
                // *** Start programmer edit section *** (ПечатьЧека.ПечатьФото Get end)

                // *** End programmer edit section *** (ПечатьЧека.ПечатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПечатьЧека.ПечатьФото Set start)

                // *** End programmer edit section *** (ПечатьЧека.ПечатьФото Set start)
                this.fПечатьФото = value;
                // *** Start programmer edit section *** (ПечатьЧека.ПечатьФото Set end)

                // *** End programmer edit section *** (ПечатьЧека.ПечатьФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПечатьЧекаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьЧекаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьЧекаE", typeof(IIS.Kursovaya3.ПечатьЧека));
                }
            }
            
            /// <summary>
            /// "ПечатьЧекаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПечатьЧекаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПечатьЧекаL", typeof(IIS.Kursovaya3.ПечатьЧека));
                }
            }
        }
    }
}
